import assert from 'node:assert/strict';
import fs from 'node:fs';
import {compileDiscoveryPlanSkeleton} from './discovery-plan-skeleton-compiler.mjs';
const fixture=new URL('../fixtures/supabase-v1/',import.meta.url);
const prepare=JSON.parse(fs.readFileSync(new URL('premium-prepare.json',fixture),'utf8'));
const sot=JSON.parse(fs.readFileSync(new URL('consultant-sot.json',fixture),'utf8'));
const catalog=JSON.parse(fs.readFileSync(new URL('../contracts/discovery-intents-v1.json',import.meta.url),'utf8'));
let r=compileDiscoveryPlanSkeleton(prepare,sot,catalog);
assert.equal(r.ok,true,JSON.stringify(r.errors));
assert.equal(r.question_slots.length,3);
assert.deepEqual(r.question_slots.map(x=>x.dimension_id),['D1','D2','D3']);
assert.equal(r.commercial_target_authorized,false);
assert(r.forbidden_primary_intents.includes('D10 economics'));
const ps=structuredClone(sot); ps.commercial_rules.budget_required_before_first_call=true;
r=compileDiscoveryPlanSkeleton(prepare,ps,catalog);
assert.equal(r.ok,true,JSON.stringify(r.errors));
assert.equal(r.question_slots.length,4);
assert.equal(r.question_slots.at(-1).dimension_id,'P_ECONOMICS');
assert.equal(r.commercial_target_authorized,true);
assert(!r.forbidden_primary_intents.includes('D10 economics'));
console.log('discovery-plan-skeleton-compiler tests: PASS');
